### PR TITLE
PIM-4886 : pinbar navigation

### PR DESCRIPTION
**Pull request by jmleroux**
| Q | A |
| --- | --- |
| Migration script? | n |
| Behats | y |
| Specs & Static | y |
| Changelog updated | n |

### CODE REVIEW

**Comment by jmleroux** [comment]
The diff on `use` statements is only because of sort order

**Comment by grena** [comment]
GTM

**Comment by nidup** [comment]
GTM

**Comment by ClementGautier** [comment]
GTM

**Pull request merged**
